---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[openstack_client::default]
    attributes:
  - name: swift
    run_list:
      - recipe[openstack_client::_example_swift]
    attributes:
  - name: nova
    run_list:
      - recipe[openstack_client::_example_nova]
    attributes:
