# Rubocop,  we're buddies and all,  but we're going to have to disagree on the following

AllCops:
 Exclude:
   - berks-cookbooks/**
   - Guardfile

Encoding:
  Exclude:
    - Gemfile

WordArray:
  MinSize: 3

Encoding:
  Exclude:
    - Gemfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

MethodLength:
  Max: 15